name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Garantir permissão de execução ao Maven Wrapper
        run: chmod +x ./mvnw

      - name: Resolver dependências, compilar e testar (Spring + Kotlin)
        run: ./mvnw -B -ntp clean verify

      - name: Gerar e enviar tag build-<timestamp>
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          TAG_NAME="build-${TIMESTAMP}"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
